GET http://localhost:3333/jokes/
###
GET http://localhost:3333/jokes/1
###
POST http://localhost:3333/jokes/1
Content-Type: application/json

{
  "joke": "Was ist ein schlechter Tag für ein U-Boot? Der Tag der offenen Tür"
}
###
PATCH http://localhost:3333/jokes/1
Content-Type: application/json

{
  "joke": "Was liegt am Strand und hat einen Sprachfehler? Eine Nuschel"
}
###
DELETE http://localhost:3333/jokes/1


